# generated by datamodel-codegen:
#   filename:  BaseItemDto.json
#   timestamp: 2026-09-13T19:49:37+00:00

# mising some context fo other types, which can be found at:
# https://jellyfin.lmrsvr.net/api-docs/openapi.json#/components/schemas/BaseItemDto
# specifically under the `components` property.

from __future__ import annotations

from typing import Any
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class ImageBlurHashes(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Primary: dict[str, str] | None = None
    Art: dict[str, str] | None = None
    Backdrop: dict[str, str] | None = None
    Banner: dict[str, str] | None = None
    Logo: dict[str, str] | None = None
    Thumb: dict[str, str] | None = None
    Disc: dict[str, str] | None = None
    Box: dict[str, str] | None = None
    Screenshot: dict[str, str] | None = None
    Menu: dict[str, str] | None = None
    Chapter: dict[str, str] | None = None
    BoxRear: dict[str, str] | None = None
    Profile: dict[str, str] | None = None


class BaseItemKind(RootModel[Any]):
    root: Any


class BaseItemPerson(RootModel[Any]):
    root: Any


class ChannelType(RootModel[Any]):
    root: Any


class ChapterInfo(RootModel[Any]):
    root: Any


class CollectionType(RootModel[Any]):
    root: Any


class DayOfWeek(RootModel[Any]):
    root: Any


class ExternalUrl(RootModel[Any]):
    root: Any


class ExtraType(RootModel[Any]):
    root: Any


class ImageOrientation(RootModel[Any]):
    root: Any


class IsoType(RootModel[Any]):
    root: Any


class LocationType(RootModel[Any]):
    root: Any


class MediaSourceInfo(RootModel[Any]):
    root: Any


class MediaStream(RootModel[Any]):
    root: Any


class MediaType(RootModel[Any]):
    root: Any


class MediaUrl(RootModel[Any]):
    root: Any


class MetadataField(RootModel[Any]):
    root: Any


class NameGuidPair(RootModel[Any]):
    root: Any


class PlayAccess(RootModel[Any]):
    root: Any


class ProgramAudio(RootModel[Any]):
    root: Any


class TrickplayInfoDto(RootModel[Any]):
    root: Any


class UserItemDataDto(RootModel[Any]):
    root: Any


class Video3DFormat(RootModel[Any]):
    root: Any


class VideoType(RootModel[Any]):
    root: Any


class BaseItemDto(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Name: str | None = Field(None, description='Gets or sets the name.')
    OriginalTitle: str | None = None
    ServerId: str | None = Field(
        None, description='Gets or sets the server identifier.'
    )
    Id: UUID = Field(description='Gets or sets the id.')
    Etag: str | None = Field(None, description='Gets or sets the etag.')
    SourceType: str | None = Field(
        None, description='Gets or sets the type of the source.'
    )
    PlaylistItemId: str | None = Field(
        None, description='Gets or sets the playlist item identifier.'
    )
    DateCreated: AwareDatetime | None = Field(
        None, description='Gets or sets the date created.'
    )
    DateLastMediaAdded: AwareDatetime | None = None
    ExtraType_1: ExtraType | None = Field(None, alias='ExtraType')
    AirsBeforeSeasonNumber: int | None = None
    AirsAfterSeasonNumber: int | None = None
    AirsBeforeEpisodeNumber: int | None = None
    CanDelete: bool | None = None
    CanDownload: bool | None = None
    HasLyrics: bool | None = None
    HasSubtitles: bool | None = None
    PreferredMetadataLanguage: str | None = None
    PreferredMetadataCountryCode: str | None = None
    Container: str | None = None
    SortName: str | None = Field(None, description='Gets or sets the name of the sort.')
    ForcedSortName: str | None = None
    Video3DFormat_1: Video3DFormat | None = Field(
        None, alias='Video3DFormat', description='Gets or sets the video3 D format.'
    )
    PremiereDate: AwareDatetime | None = Field(
        None, description='Gets or sets the premiere date.'
    )
    ExternalUrls: list[ExternalUrl] | None = Field(
        None, description='Gets or sets the external urls.'
    )
    MediaSources: list[MediaSourceInfo] | None = Field(
        None, description='Gets or sets the media versions.'
    )
    CriticRating: float | None = Field(
        None, description='Gets or sets the critic rating.'
    )
    ProductionLocations: list[str] | None = None
    Path: str | None = Field(None, description='Gets or sets the path.')
    EnableMediaSourceDisplay: bool | None = None
    OfficialRating: str | None = Field(
        None, description='Gets or sets the official rating.'
    )
    CustomRating: str | None = Field(
        None, description='Gets or sets the custom rating.'
    )
    ChannelId: UUID | None = Field(
        None, description='Gets or sets the channel identifier.'
    )
    ChannelName: str | None = None
    Overview: str | None = Field(None, description='Gets or sets the overview.')
    Taglines: list[str] | None = Field(None, description='Gets or sets the taglines.')
    Genres: list[str] | None = Field(None, description='Gets or sets the genres.')
    CommunityRating: float | None = Field(
        None, description='Gets or sets the community rating.'
    )
    CumulativeRunTimeTicks: int | None = Field(
        None, description='Gets or sets the cumulative run time ticks.'
    )
    RunTimeTicks: int | None = Field(
        None, description='Gets or sets the run time ticks.'
    )
    PlayAccess_1: PlayAccess | None = Field(
        None, alias='PlayAccess', description='Gets or sets the play access.'
    )
    AspectRatio: str | None = Field(None, description='Gets or sets the aspect ratio.')
    ProductionYear: int | None = Field(
        None, description='Gets or sets the production year.'
    )
    IsPlaceHolder: bool | None = Field(
        None,
        description='Gets or sets a value indicating whether this instance is place holder.',
    )
    Number: str | None = Field(None, description='Gets or sets the number.')
    ChannelNumber: str | None = None
    IndexNumber: int | None = Field(None, description='Gets or sets the index number.')
    IndexNumberEnd: int | None = Field(
        None, description='Gets or sets the index number end.'
    )
    ParentIndexNumber: int | None = Field(
        None, description='Gets or sets the parent index number.'
    )
    RemoteTrailers: list[MediaUrl] | None = Field(
        None, description='Gets or sets the trailer urls.'
    )
    ProviderIds: dict[str, str] | None = Field(
        None, description='Gets or sets the provider ids.'
    )
    IsHD: bool | None = Field(
        None, description='Gets or sets a value indicating whether this instance is HD.'
    )
    IsFolder: bool | None = Field(
        None,
        description='Gets or sets a value indicating whether this instance is folder.',
    )
    ParentId: UUID | None = Field(None, description='Gets or sets the parent id.')
    Type: BaseItemKind | None = Field(None, description='Gets or sets the type.')
    People: list[BaseItemPerson] | None = Field(
        None, description='Gets or sets the people.'
    )
    Studios: list[NameGuidPair] | None = Field(
        None, description='Gets or sets the studios.'
    )
    GenreItems: list[NameGuidPair] | None = None
    ParentLogoItemId: UUID | None = Field(
        None,
        description='Gets or sets whether the item has a logo, this will hold the Id of the Parent that has one.',
    )
    ParentBackdropItemId: UUID | None = Field(
        None,
        description='Gets or sets whether the item has any backdrops, this will hold the Id of the Parent that has one.',
    )
    ParentBackdropImageTags: list[str] | None = Field(
        None, description='Gets or sets the parent backdrop image tags.'
    )
    LocalTrailerCount: int | None = Field(
        None, description='Gets or sets the local trailer count.'
    )
    UserData: UserItemDataDto | None = Field(
        None,
        description="Gets or sets the user data for this item based on the user it's being requested for.",
    )
    RecursiveItemCount: int | None = Field(
        None, description='Gets or sets the recursive item count.'
    )
    ChildCount: int | None = Field(None, description='Gets or sets the child count.')
    SeriesName: str | None = Field(
        None, description='Gets or sets the name of the series.'
    )
    SeriesId: UUID | None = Field(None, description='Gets or sets the series id.')
    SeasonId: UUID | None = Field(
        None, description='Gets or sets the season identifier.'
    )
    SpecialFeatureCount: int | None = Field(
        None, description='Gets or sets the special feature count.'
    )
    DisplayPreferencesId: str | None = Field(
        None, description='Gets or sets the display preferences id.'
    )
    Status: str | None = Field(None, description='Gets or sets the status.')
    AirTime: str | None = Field(None, description='Gets or sets the air time.')
    AirDays: list[DayOfWeek] | None = Field(
        None, description='Gets or sets the air days.'
    )
    Tags: list[str] | None = Field(None, description='Gets or sets the tags.')
    PrimaryImageAspectRatio: float | None = Field(
        None,
        description='Gets or sets the primary image aspect ratio, after image enhancements.',
    )
    Artists: list[str] | None = Field(None, description='Gets or sets the artists.')
    ArtistItems: list[NameGuidPair] | None = Field(
        None, description='Gets or sets the artist items.'
    )
    Album: str | None = Field(None, description='Gets or sets the album.')
    CollectionType_1: CollectionType | None = Field(
        None,
        alias='CollectionType',
        description='Gets or sets the type of the collection.',
    )
    DisplayOrder: str | None = Field(
        None, description='Gets or sets the display order.'
    )
    AlbumId: UUID | None = Field(None, description='Gets or sets the album id.')
    AlbumPrimaryImageTag: str | None = Field(
        None, description='Gets or sets the album image tag.'
    )
    SeriesPrimaryImageTag: str | None = Field(
        None, description='Gets or sets the series primary image tag.'
    )
    AlbumArtist: str | None = Field(None, description='Gets or sets the album artist.')
    AlbumArtists: list[NameGuidPair] | None = Field(
        None, description='Gets or sets the album artists.'
    )
    SeasonName: str | None = Field(
        None, description='Gets or sets the name of the season.'
    )
    MediaStreams: list[MediaStream] | None = Field(
        None, description='Gets or sets the media streams.'
    )
    VideoType_1: VideoType | None = Field(
        None, alias='VideoType', description='Gets or sets the type of the video.'
    )
    PartCount: int | None = Field(None, description='Gets or sets the part count.')
    MediaSourceCount: int | None = None
    ImageTags: dict[str, str] | None = Field(
        None, description='Gets or sets the image tags.'
    )
    BackdropImageTags: list[str] | None = Field(
        None, description='Gets or sets the backdrop image tags.'
    )
    ScreenshotImageTags: list[str] | None = Field(
        None, description='Gets or sets the screenshot image tags.'
    )
    ParentLogoImageTag: str | None = Field(
        None, description='Gets or sets the parent logo image tag.'
    )
    ParentArtItemId: UUID | None = Field(
        None,
        description='Gets or sets whether the item has fan art, this will hold the Id of the Parent that has one.',
    )
    ParentArtImageTag: str | None = Field(
        None, description='Gets or sets the parent art image tag.'
    )
    SeriesThumbImageTag: str | None = Field(
        None, description='Gets or sets the series thumb image tag.'
    )
    ImageBlurHashes_1: ImageBlurHashes | None = Field(
        None,
        alias='ImageBlurHashes',
        description='Gets or sets the blurhashes for the image tags.\nMaps image type to dictionary mapping image tag to blurhash value.',
    )
    SeriesStudio: str | None = Field(
        None, description='Gets or sets the series studio.'
    )
    ParentThumbItemId: UUID | None = Field(
        None, description='Gets or sets the parent thumb item id.'
    )
    ParentThumbImageTag: str | None = Field(
        None, description='Gets or sets the parent thumb image tag.'
    )
    ParentPrimaryImageItemId: UUID | None = Field(
        None, description='Gets or sets the parent primary image item identifier.'
    )
    ParentPrimaryImageTag: str | None = Field(
        None, description='Gets or sets the parent primary image tag.'
    )
    Chapters: list[ChapterInfo] | None = Field(
        None, description='Gets or sets the chapters.'
    )
    Trickplay: dict[str, dict[str, TrickplayInfoDto]] | None = Field(
        None, description='Gets or sets the trickplay manifest.'
    )
    LocationType_1: LocationType | None = Field(
        None, alias='LocationType', description='Gets or sets the type of the location.'
    )
    IsoType_1: IsoType | None = Field(
        None, alias='IsoType', description='Gets or sets the type of the iso.'
    )
    MediaType_1: MediaType | None = Field(
        'Unknown',
        alias='MediaType',
        description='Gets or sets the type of the media.',
        validate_default=True,
    )
    EndDate: AwareDatetime | None = Field(
        None, description='Gets or sets the end date.'
    )
    LockedFields: list[MetadataField] | None = Field(
        None, description='Gets or sets the locked fields.'
    )
    TrailerCount: int | None = Field(
        None, description='Gets or sets the trailer count.'
    )
    MovieCount: int | None = Field(None, description='Gets or sets the movie count.')
    SeriesCount: int | None = Field(None, description='Gets or sets the series count.')
    ProgramCount: int | None = None
    EpisodeCount: int | None = Field(
        None, description='Gets or sets the episode count.'
    )
    SongCount: int | None = Field(None, description='Gets or sets the song count.')
    AlbumCount: int | None = Field(None, description='Gets or sets the album count.')
    ArtistCount: int | None = None
    MusicVideoCount: int | None = Field(
        None, description='Gets or sets the music video count.'
    )
    LockData: bool | None = Field(
        None,
        description='Gets or sets a value indicating whether [enable internet providers].',
    )
    Width: int | None = None
    Height: int | None = None
    CameraMake: str | None = None
    CameraModel: str | None = None
    Software: str | None = None
    ExposureTime: float | None = None
    FocalLength: float | None = None
    ImageOrientation_1: ImageOrientation | None = Field(None, alias='ImageOrientation')
    Aperture: float | None = None
    ShutterSpeed: float | None = None
    Latitude: float | None = None
    Longitude: float | None = None
    Altitude: float | None = None
    IsoSpeedRating: int | None = None
    SeriesTimerId: str | None = Field(
        None, description='Gets or sets the series timer identifier.'
    )
    ProgramId: str | None = Field(
        None, description='Gets or sets the program identifier.'
    )
    ChannelPrimaryImageTag: str | None = Field(
        None, description='Gets or sets the channel primary image tag.'
    )
    StartDate: AwareDatetime | None = Field(
        None, description='Gets or sets the start date of the recording, in UTC.'
    )
    CompletionPercentage: float | None = Field(
        None, description='Gets or sets the completion percentage.'
    )
    IsRepeat: bool | None = Field(
        None,
        description='Gets or sets a value indicating whether this instance is repeat.',
    )
    EpisodeTitle: str | None = Field(
        None, description='Gets or sets the episode title.'
    )
    ChannelType_1: ChannelType | None = Field(
        None, alias='ChannelType', description='Gets or sets the type of the channel.'
    )
    Audio: ProgramAudio | None = Field(None, description='Gets or sets the audio.')
    IsMovie: bool | None = Field(
        None,
        description='Gets or sets a value indicating whether this instance is movie.',
    )
    IsSports: bool | None = Field(
        None,
        description='Gets or sets a value indicating whether this instance is sports.',
    )
    IsSeries: bool | None = Field(
        None,
        description='Gets or sets a value indicating whether this instance is series.',
    )
    IsLive: bool | None = Field(
        None,
        description='Gets or sets a value indicating whether this instance is live.',
    )
    IsNews: bool | None = Field(
        None,
        description='Gets or sets a value indicating whether this instance is news.',
    )
    IsKids: bool | None = Field(
        None,
        description='Gets or sets a value indicating whether this instance is kids.',
    )
    IsPremiere: bool | None = Field(
        None,
        description='Gets or sets a value indicating whether this instance is premiere.',
    )
    TimerId: str | None = Field(None, description='Gets or sets the timer identifier.')
    NormalizationGain: float | None = Field(
        None, description='Gets or sets the gain required for audio normalization.'
    )
    AlbumNormalizationGain: float | None = Field(
        None,
        description='Gets or sets the gain required for audio normalization. This field is inherited from music album normalization gain.',
    )
    CurrentProgram: BaseItemDto | None = Field(
        None, description='Gets or sets the current program.'
    )
    OriginalLanguage: str | None = None
